# Generated by Django 3.2.8 on 2021-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211104_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name_plural': 'Mahsulot Turi'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
