# Generated by Django 3.2.8 on 2021-11-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211104_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
